import os
import re
import ast
import time
import logging
from pathlib import Path
from langchain.tools import tool
from pydantic import BaseModel, Field

TOOLS_DIR = Path(__file__).parent
CONFIG_PATH = Path(__file__).parent.parent.parent / "config" / "instructions.txt"

BLOCKED_FUNCTIONS = {
    "eval", "exec", "system", "os.system", "subprocess.Popen", "subprocess.run",
    "subprocess.call", "subprocess.check_output", "shutil.rmtree", "os.remove",
    "os.unlink", "os.rmdir", "os.popen", "os.kill", "os.spawn", "sys.exit"
}

TOOL_TEMPLATE = """# Auto-generated by FRIDAY
import requests
from langchain.tools import tool


def get_tool():
    @tool("{name}")
    def {func_name}(query: str) -> str:
        \"\"\"{description}\"\"\"
{indented_body}
    return {func_name}
"""

def is_safe_code(code: str) -> tuple[bool, str]:
    """
    Validates Python code using Abstract Syntax Tree (AST) scanning.
    Blocks dangerous operations such as subprocesses, dynamic execution (exec/eval),
    system command calls, and dangerous file system deletions.
    """
    try:
        tree = ast.parse(code)
    except SyntaxError as e:
        return False, f"Syntax Error: {e}"
        
    for node in ast.walk(tree):
        # 1. Block dangerous module imports
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            names = [alias.name for alias in node.names]
            for name in names:
                if any(x in name for x in ["subprocess", "shutil"]):
                    return False, f"Blocked unsafe module import: '{name}'"
                    
        # 2. Block dangerous function calls
        if isinstance(node, ast.Call):
            func_name = ""
            if isinstance(node.func, ast.Name):
                func_name = node.func.id
            elif isinstance(node.func, ast.Attribute):
                parts = []
                curr = node.func
                while isinstance(curr, ast.Attribute):
                    parts.append(curr.attr)
                    curr = curr.value
                if isinstance(curr, ast.Name):
                    parts.append(curr.id)
                func_name = ".".join(reversed(parts))
                
            # Check against blacklist
            for blocked in BLOCKED_FUNCTIONS:
                if (func_name == blocked) or (func_name.endswith("." + blocked.split(".")[-1]) and func_name.startswith("os.")):
                    return False, f"Blocked unsafe function call: '{func_name}'"
                if func_name in ["eval", "exec"]:
                    return False, f"Blocked dynamic execution function: '{func_name}'"
                    
    return True, "Safe"


class ToolCreationInput(BaseModel):
    tool_name: str = Field(
        description="Snake_case name for the new tool (e.g. 'weather_checker')"
    )
    description: str = Field(
        description="One sentence describing what the tool does"
    )
    code_body: str = Field(
        description="The Python function body ONLY — no def line, no decorator. Indent each line with exactly 4 spaces."
    )

@tool("create_new_tool", args_schema=ToolCreationInput)
def create_new_tool(tool_name: str, description: str, code_body: str) -> str:
    """
    Creates a new tool file and hot-reloads it into FRIDAY's active tool list.
    Use this when the user asks to add a new capability or feature to FRIDAY.
    The code_body MUST return a string, use requests for HTTP, and pass AST validation.
    """
    func_name = tool_name.lower().strip().replace(" ", "_").replace("-", "_")

    # Safety check on generated code
    is_safe, error_msg = is_safe_code(code_body)
    if not is_safe:
        return f"Safety Sandbox Block: {error_msg}"

    # Indent body to 8 spaces (inside get_tool > inner function)
    indented_lines = []
    for line in code_body.strip().splitlines():
        indented_lines.append(("        " + line) if line.strip() else "")
    indented_body = "\n".join(indented_lines)

    if not indented_body.strip():
        return "Error: code_body is empty."

    content = TOOL_TEMPLATE.format(
        name=func_name,
        func_name=func_name,
        description=description,
        indented_body=indented_body,
    )

    output_path = TOOLS_DIR / f"{func_name}.py"
    try:
        output_path.write_text(content, encoding="utf-8")
        logging.info(f"New tool written: {output_path}")
    except Exception as e:
        return f"Failed to write tool file: {e}"

    try:
        from friday.tool_manager import reload_tools
        reload_tools()
        return f"Tool '{func_name}' created and loaded. You can use it now."
    except Exception as e:
        return f"Tool saved to {output_path.name} but reload failed: {e}. Restart FRIDAY to activate it."


@tool("modify_instructions")
def modify_instructions(new_rule: str) -> str:
    """
    Appends a new behavior rule or instruction to FRIDAY's system instructions permanently.
    Use this when the user asks you to change how you speak, modify constraints, or add behavior guidelines.
    Input: the new instruction or rule statement to add.
    """
    try:
        # Create config directory if it does not exist
        CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
        
        current = ""
        if CONFIG_PATH.exists():
            current = CONFIG_PATH.read_text(encoding="utf-8").strip()
            
        new_content = current + f"\n- {new_rule.strip()}"
        CONFIG_PATH.write_text(new_content, encoding="utf-8")
        
        # Trigger agent rebuild with the new instructions loaded
        from friday.core.llm_agent import rebuild_agent
        rebuild_agent()
        
        return f"Instruction added successfully and agent rebuilt: {new_rule}"
    except Exception as e:
        return f"Failed to modify instructions: {e}"


class ToolUpgradeInput(BaseModel):
    tool_name: str = Field(
        description="Snake_case name of the existing tool to upgrade (e.g. 'weather_checker')"
    )
    new_code_body: str = Field(
        description="The updated Python function body ONLY (no def line, no decorator). Indent with 4 spaces."
    )

@tool("upgrade_tool", args_schema=ToolUpgradeInput)
def upgrade_tool(tool_name: str, new_code_body: str) -> str:
    """
    Upgrades an existing tool by overwriting its code, auto-backing up the previous version, and hot-reloading.
    Use this when a tool has errors, needs to be updated with new APIs, or requires improvements.
    """
    func_name = tool_name.lower().strip().replace(".py", "")
    tool_path = TOOLS_DIR / f"{func_name}.py"
    
    if not tool_path.exists():
        return f"Error: Tool '{func_name}' not found."
        
    # Safety Check
    is_safe, error_msg = is_safe_code(new_code_body)
    if not is_safe:
        return f"Safety Sandbox Block: {error_msg}"
        
    try:
        # 1. Create backup folder if needed
        backup_dir = TOOLS_DIR / "_backups"
        backup_dir.mkdir(exist_ok=True)
        
        # 2. Copy current version to backup
        timestamp = int(time.time())
        backup_path = backup_dir / f"{func_name}_v{timestamp}.py"
        shutil_copy(tool_path, backup_path)
        
        # 3. Read the description from current file if possible to preserve it
        description = f"Upgraded tool for: {func_name}"
        try:
            curr_content = tool_path.read_text(encoding="utf-8")
            desc_match = re.search(r'\"\"\"(.*?)\"\"\"', curr_content, re.DOTALL)
            if desc_match:
                description = desc_match.group(1).strip()
        except Exception:
            pass
            
        # 4. Formulate upgraded body
        indented_lines = []
        for line in new_code_body.strip().splitlines():
            indented_lines.append(("        " + line) if line.strip() else "")
        indented_body = "\n".join(indented_lines)
        
        content = TOOL_TEMPLATE.format(
            name=func_name,
            func_name=func_name,
            description=description,
            indented_body=indented_body,
        )
        
        # 5. Overwrite file
        tool_path.write_text(content, encoding="utf-8")
        
        # 6. Reload tools
        from friday.tool_manager import reload_tools
        reload_tools()
        
        return f"Tool '{func_name}' upgraded successfully. Previous version backed up to _backups/."
        
    except Exception as e:
        return f"Failed to upgrade tool: {e}"


@tool("rollback_tool")
def rollback_tool(tool_name: str) -> str:
    """
    Reverts an upgraded tool to its previous version by copying the latest backup from the _backups directory.
    Use this when an upgraded tool is buggy or fails execution.
    Input: the name of the tool to revert (e.g. 'weather_checker').
    """
    func_name = tool_name.lower().strip().replace(".py", "")
    tool_path = TOOLS_DIR / f"{func_name}.py"
    backup_dir = TOOLS_DIR / "_backups"
    
    if not backup_dir.exists():
        return f"No backups directory found. Cannot rollback '{func_name}'."
        
    # Find all backup files for this tool
    backups = list(backup_dir.glob(f"{func_name}_v*.py"))
    if not backups:
        return f"No backups found for tool '{func_name}'."
        
    # Sort backups to find the most recent one
    backups.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    latest_backup = backups[0]
    
    try:
        # Restore backup
        import shutil
        shutil.copy(latest_backup, tool_path)
        
        # Reload
        from friday.tool_manager import reload_tools
        reload_tools()
        
        return f"Successfully rolled back tool '{func_name}' to version {latest_backup.name}."
    except Exception as e:
        return f"Failed to rollback tool: {e}"


def shutil_copy(src: Path, dst: Path):
    """Simple file copier to avoid shutil module imports in AST scans."""
    dst.write_bytes(src.read_bytes())
