# Auto-generated by FRIDAY (fixed)
import requests
from langchain.tools import tool


def get_tool():
    @tool("weather_checker")
    def weather_checker(query: str) -> str:
        """Returns the current weather for a city or location. Input should be a city name."""
        try:
            url = f"https://wttr.in/{query}?format=%l:+%C,+%t,+feels+like+%f,+humidity+%h,+wind+%w"
            resp = requests.get(url, timeout=6, headers={"User-Agent": "curl/7.68.0"})
            if resp.status_code == 200:
                return resp.text.strip()
            return f"Could not fetch weather for {query} (status {resp.status_code})."
        except Exception as e:
            return f"Weather fetch failed: {e}"
    return weather_checker
