import logging
from pathlib import Path
from langchain.tools import tool
from pydantic import BaseModel, Field

TOOLS_DIR = Path(__file__).parent

BLOCKED_PATTERNS = [
    "os.system(",
    "subprocess.Popen",
    "subprocess.run(",
    "subprocess.call(",
    "shutil.rmtree",
    "exec(",
    "eval(",
    "__import__(",
    "sys.exit(",
    "os.remove(",
    "os.unlink(",
]

TOOL_TEMPLATE = """\
# Auto-generated by FRIDAY
import requests
from langchain.tools import tool


def get_tool():
    @tool("{name}")
    def {func_name}(query: str) -> str:
        \"\"\"{description}\"\"\"
{indented_body}
    return {func_name}
"""


class ToolCreationInput(BaseModel):
    tool_name: str = Field(
        description="Snake_case name for the new tool (e.g. 'weather_checker')"
    )
    description: str = Field(
        description="One sentence describing what the tool does"
    )
    code_body: str = Field(
        description=(
            "The Python function body ONLY — no def line, no decorator. "
            "Rules: "
            "(1) MUST end with a return statement that returns a string. "
            "(2) Use the 'requests' library (already imported) to fetch data from APIs. "
            "(3) Never open browsers or GUIs — fetch and return text only. "
            "(4) Wrap everything in try/except and return an error string on failure. "
            "(5) Indent each line with exactly 4 spaces. "
            "Example for a weather tool body: "
            "    try:\n"
            "        resp = requests.get(f'https://wttr.in/{query}?format=3', timeout=6)\n"
            "        return resp.text.strip()\n"
            "    except Exception as e:\n"
            "        return f'Failed: {e}'"
        )
    )


@tool("create_new_tool", args_schema=ToolCreationInput)
def create_new_tool(tool_name: str, description: str, code_body: str) -> str:
    """
    Creates a new tool file and hot-reloads it into FRIDAY's active tool list.
    Use this when the user asks to add a new capability or feature to FRIDAY.
    The code_body MUST return a string and use requests for any HTTP calls.
    Never open browsers or GUIs. Always wrap in try/except.
    After calling this, the new tool is immediately available.
    """
    func_name = tool_name.lower().strip().replace(" ", "_").replace("-", "_")

    # Safety check on generated code
    for pattern in BLOCKED_PATTERNS:
        if pattern in code_body:
            return f"Blocked: generated code contains disallowed pattern '{pattern}'."

    # Indent body to 8 spaces (inside get_tool > inner function)
    indented_lines = []
    for line in code_body.strip().splitlines():
        indented_lines.append(("        " + line) if line.strip() else "")
    indented_body = "\n".join(indented_lines)

    if not indented_body.strip():
        return "Error: code_body is empty."

    content = TOOL_TEMPLATE.format(
        name=func_name,
        func_name=func_name,
        description=description,
        indented_body=indented_body,
    )

    output_path = TOOLS_DIR / f"{func_name}.py"
    try:
        output_path.write_text(content, encoding="utf-8")
        logging.info(f"New tool written: {output_path}")
    except Exception as e:
        return f"Failed to write tool file: {e}"

    try:
        from friday.tool_manager import reload_tools
        reload_tools()
        return f"Tool '{func_name}' created and loaded. You can use it now."
    except Exception as e:
        return f"Tool saved to {output_path.name} but reload failed: {e}. Restart FRIDAY to activate it."
